### ISSUE TITLE
500: Internal Server Error while exporting notebook.

### ISSUE THREAD

**Issue by ant10484** [kirbs-/hide_code#42] opened 2017-10-03 18:30 UTC
Hi, 
You have done an amazing job with hide_code. Thanks for that.

I am having 500 error whenever I try to export a notebook via the buttons on the notebook.
I am using nbconvert 4.3.0, python 3.6 and notebook 5.0.

I am able to export using the command below:
jupyter nbconvert --to hide_code_pdf notebook_to_convert.ipynb

It's just that I am unable to use the  buttons on the notebook to export as a pdf or html.

I tried restarting and installed hide_code multiple times but I am unable to find a solution.
I tried the command "jupyter nbextension list"
My output is below:
Known nbextensions:
  config dir: C:\Users\antho\.jupyter\nbconfig
    notebook section
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/m
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
      hide_input/main disabled
      execute_time/ExecuteTime enabled
      - Validating: ok
      hide_code/hide_code enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
      tree-filter/index enabled
      - Validating: ok
  config dir: C:\ProgramData\Anaconda3\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/m
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: C:\ProgramData\jupyter\nbconfig
    notebook section
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/m
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main

Kindly guide where I am going wrong.
Thanks alot for your precious time and effort.

**Comment by p2ya** [comment] 2017-10-04 01:08
I am experiencing the same issue, really appreciate if can help to resolve this

**Comment by kirbs-** [comment] 2017-10-04 02:11
Please post the output from the Jupyter console when you see the error. Also, check out the dev branch. The 0.5.0 release is just about ready. See if that fixes the issue.

**Comment by p2ya** [comment] 2017-10-04 02:26
Also how can I install the dev version ?

**Comment by kirbs-** [comment] 2017-10-04 02:44
This looks like an issue with wkhtmltopdf. Does exporting to pdf latex work for you?

**Comment by p2ya** [comment] 2017-10-04 02:44
yes that one does work.

**Comment by kirbs-** [comment] 2017-10-04 02:51
Are you using a secure notebook? Looks like wkhtmltopdf is failing due to an SSL error.

**Comment by ant10484** [comment] 2017-10-04 08:41
Hi,
Thanks for your prompt reply. 
Below is my output whenever I try to save the notebook to pdf using the buttons on the notebook browser.
[I 14:06:22.579 NotebookApp] Kernel started: a508b75c-cc1f-48a6-9b90-c75f6b9ef838
[I 14:06:34.327 NotebookApp] hide_code: Starting PDF export for /Introducing_Python_Book.ipynb
[E 14:06:34.335 NotebookApp] Uncaught exception GET /notebooks/Desktop/pythonx/Introducing_Python_Book.ipynb/export/pdf (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Desktop/pythonx/Introducing_Python_Book.ipynb/export/pdf', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Referer': 'http://localhost:8888/notebooks/Desktop/pythonx/Introducing_Python_Book.ipynb', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.8', 'Cookie': '_xsrf=2|67cdb8d0|e84f95f10047f41dc519a8bf42b09c59|1507052138; username-localhost-8888="2|1:0|10:1507105994|23:username-localhost-8888|44:OWJmYTYxZWIzNzRkNDVhZjhiNDJkYjNhYzE3OGU1ZGU=|a2ad77ac0933aef10e5df55f66cf5e70d471ea99d8466c4b3b973350df2c951a"'})
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\hide_code\hide_code.py", line 36, in get
        with open(ipynb_file_name(args)) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'Desktop\\pythonx\\Introducing_Python_Book.ipynb'
[E 14:06:34.351 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Referer": "http://localhost:8888/notebooks/Desktop/pythonx/Introducing_Python_Book.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.8",
      "Cookie": "_xsrf=2|67cdb8d0|e84f95f10047f41dc519a8bf42b09c59|1507052138; username-localhost-8888=\"2|1:0|10:1507105994|23:username-localhost-8888|44:OWJmYTYxZWIzNzRkNDVhZjhiNDJkYjNhYzE3OGU1ZGU=|a2ad77ac0933aef10e5df55f66cf5e70d471ea99d8466c4b3b973350df2c951a\""
    }
[E 14:06:34.355 NotebookApp] 500 GET /notebooks/Desktop/pythonx/Introducing_Python_Book.ipynb/export/pdf (::1) 24.00ms referer=http://localhost:8888/notebooks/Desktop/pythonx/Introducing_Python_Book.ipynb

Thanks.

**Comment by kirbs-** [comment] 2017-10-07 19:23
Please upgrade to 0.5.0. I think this is related to #38.

**Comment by p2ya** [comment] 2017-10-09 00:57
I installed through:
pip install hide_code --upgrade

however the issue is still reoccurring

**Comment by kirbs-** [comment] 2017-11-04 23:29
I'm closing this issue out since the 500 error is resolved.

**Closed by kirbs-** 2017-11-04 23:29 UTC
