### ISSUE TITLE
Can not change cell toolbar back to none after toggling hide/show

### ISSUE THREAD

**Issue by ruffsl** [kirbs-/hide_code#11] opened 2016-02-09 04:55 UTC
I'm experiencing an odd behavior where once I've a non-`None` cell toolbar view selected, then toggle the hide/show code button, I can no longer switch cell toolbar view back to `None`. Here is a gif of an example:

![anim](https://cloud.githubusercontent.com/assets/2293573/12907807/b976ffac-cebd-11e5-93ab-60416d2d22e0.gif)

System info:
* hide_code: commit 52e071ce9c1c1236a0b6978f64dbe9d96e85c151
* Jupyter/IPython:
```condole
$ conda list | grep jupyter
jupyter                   1.0.0                    py35_1  
jupyter-client            4.1.1                     <pip>
jupyter-console           4.1.0                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py35_0  
jupyter_console           4.1.0                    py35_0  
jupyter_core              4.0.6                    py35_0 
$ conda list | grep ipython
ipython                   4.0.3                    py35_0  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py35_0  
ipython-qtconsole         4.0.1                    py35_0  
ipython_genutils          0.1.0                    py35_0
```
* Conda: 
```command
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/ubuntu/anaconda3  (writable)
  default environment : /home/ubuntu/anaconda3
     envs directories : /home/ubuntu/anaconda3/envs
        package cache : /home/ubuntu/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```
* Firefox: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0)

**Comment by kirbs-** [comment] 2016-02-10 01:19
That's odd. The JS that toggles the code hiding is a simple jQuery toggle(). I'll take a look though.

**Comment by kirbs-** [comment] 2016-03-03 22:29
@ruffsl would you install the dev branch and see if the issue is fixed on your end? Thanks!

**Comment by ruffsl** [comment] 2016-03-03 22:59
I think is more stable, as I no longer encounter the lockup above. 
The only trip up I found could cause was:
(From fresh opened notebook)
 1. [Toggle `hide/show code`: ON]
 * [Change 'Cell Toolbar' to something other than `None`, like `Slideshow`] 
 * [Toggle `hide/show code`: OFF] 
 * (Note: 'Cell Toolbar' still appears to be `None`) 
 * [Correct this by resetting 'Cell Toolbar' to `Slideshow`] 
 * (Note: Change of 'Cell Toolbar' is only effective while `hide/show code`: OFF)

I don't think this is unreasonable; changing of setting only effecting states if visible. It just might not be at an expected UI behavior. Thanks though!

**Comment by kirbs-** [comment] 2016-03-04 02:05
Yeah, that is intentional behavior. I'll add a note in the documentation.

**Closed** 2016-03-04 02:22 UTC
Labels: bug
