### ISSUE TITLE
Exporting Issues (Unknown exporter "hide_code_latexpdf".

### ISSUE THREAD

**Issue by GalvinGao** [kirbs-/hide_code#73] opened 2019-02-13 16:45 UTC
```
jupyter nbconvert --to hide_code_latexpdf MyNotebook.ipynb
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\ProgramData\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 325, in start
    self.convert_notebooks()
  File "D:\ProgramData\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 482, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\base.py", line 110, in get_exporter
    % (name, ', '.join(get_export_names())))
ValueError: Unknown exporter "hide_code_latexpdf", did you mean one of: asciidoc, custom, hide_code_html, hide_code_latex, hide_code_pdf, hide_code_slides, html, html_ch, html_embed, html_toc, html_with_lenvs, html_with_toclenvs, latex, latex_with_lenvs, markdown, notebook, pdf, python, rst, script, selectLanguage, slides, slides_with_lenvs?
```

**Comment by martinorpa** [comment] 2019-02-21 03:15
just

on any folder run 

> git clone https://github.com/kirbs-/hide_code
> cd hide_code
> pip install -e . 
(or incase of python3 then > pip3 install -e . )

**Comment by kirbs-** [comment] 2020-02-15 20:05
Duplicate of #65

**Closed by kirbs-** 2020-02-15 20:05 UTC
Labels: bug
